services:
  regression_one:
    image: python:3.10-alpine
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "pytest -s -v tests/* --alluredir=allure-results"

  regression_two:
    image: python:3.10-alpine
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "pytest -s -v tests/* --alluredir=allure-results"
