version: "3.8"

services:
  regression:
    image: python:3.10-alpine
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./:usr/lessons
    command: /bin/sh -c "ls -la && pytest -s -v tests/* --alluredir=allure-results"
#    working_dir: /usr/lessons
