name: Pytest-Home

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  home-tests:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [20.x]

    # копируем код на виртуальную машину
    steps:
      - uses: actions/checkout@v4

      - name: Run_tests_by_docker-compose

        # продолжать работу - если ошибка
        run: | 
          docker-compose up --exit-code-from regression || True

      - name: Generate_Allure_Report
        run: |
          sudo docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      # из документации git -> create [CI_TOKEN] before
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
